Add LaTeX macros and option to pass quick_and_dirty
astahfrom/isasnips pull request #1
Opened 2021-06-30 15:55 UTC by fkj

This PR is actually two separate changes.

First, Isabelle currently generates some LaTeX macros that are undefined, so the recommended LaTeX should include definitions for these macros.

Second, for unfinished theories, Isabelle needs the `quick_and_dirty` flag before it will build.
I have added a flag to isasnips that allows the user to pass this flag to Isabelle.

2021-07-13 12:26 UTC, astahfrom requested changes

2021-07-13 12:26 UTC, astahfrom commented on README.md
> +% Isabelle currently generates some undefined macros, so we just define them to be empty:
This depends on your template, so I would prefer to put these in a separate code block.
In many cases one does not need these definitions.

2021-07-15 14:31 UTC, fkj commented on README.md
> +% Isabelle currently generates some undefined macros, so we just define them to be empty:
I have moved them into a separate code block with a line explaining this.

2021-07-15 14:34 UTC, astahfrom requested changes
I would prefer that the option is called "-quick-and-dirty" with hyphens rather than underscores. Do you feel strongly about having it match Isabelle?

2021-07-15 14:41 UTC, fkj commented
I don't really care any way or the other, but it is perhaps more intuitive that it matches Isabelle.
How about allowing both?

2021-07-15 14:43 UTC, astahfrom commented
Both sounds good! Linux binutils use hyphens, so I want to allow for that as well.

2021-07-15 14:52 UTC, astahfrom approved these changes

2021-07-15 14:52 UTC, merged